baseURL = "https://cybernetic.coffee/"
languageCode = "en-us"
title = "Cybernetic Coffee"
theme = "cybernetic-coffee"

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"


#[permalinks]
#    posts = "/posts/:year/:month/:title/"

lastModDisplay = "Modified:"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"


buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true

enableSharingButtons = true

defaultTheme = "dark"
themeColor = "#252627"

footerLeft = " "
footerRight = "Hacked together with &#10084; by <a href=\"https://github.com/Angus-C-git\">Angus C</a>"


  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/ghostinthefiber"

  [[params.social]]
    name = "github"
    url  = "https://github.com/Angus-C-git"

  [[params.social]]
    name = "ctftime"
    url  = "https://ctftime.org/team/122125"



[languages]
    [languages.en]
        # copyright = " "
    

    [languages.en.params.logo]
      logoText = "Cybernetic"
      logoCursorColor = "#00ba68"

[[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog"

[[menu.main]]
    identifier = "Capture The Flag"
    name       = "CTF"
    url        = "/ctf"

